version: '2'

services:

    redis:
        image: redis:3.2-alpine
        volumes:
            - /etc/localtime:/etc/localtime:ro
#            - /data/docker/postgres/discourse-demo:/var/lib/postgresql/data
            - ./data/redis:/var/lib/redis:Z

    postgres:
        image: postgres:9.6-alpine
        volumes: 
            - /etc/localtime:/etc/localtime:ro
#            - /data/docker/postgres/discourse-demo:/var/lib/postgresql/data
            - ./data/postgres:/var/lib/postgresql/data:Z
        environment:
            - POSTGRES_USER=discourse
            - POSTGRES_PASSWORD=p4ssw0rd
    
    discourse:
        build: app
        image: leopku/discourse:1.3.10-official
        # image: discourse/discourse:1.3.10
        # entrypoint: ./entrypoint.sh
        depends_on:
            - redis
            - postgres
        links:
            - redis:redis
            - postgres:postgres
        # command: ["./wait-for-it.sh", "postgres:"]
        expose:
            - "80"
            - "443"