version: '2.0'

services:

    redis:
        image: redis:3.2-alpine
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./volumes/redis:/var/lib/redis:Z

    db:
        image: postgres:9.6
        volumes: 
            - /etc/localtime:/etc/localtime:ro
            - ./volumes/postgres/data:/var/lib/postgresql/data:Z
        env_file:
            - .env

    mail:
        image: mailhog/mailhog
        volumes:
            - /etc/localtime:/etc/localtime:ro
        ports:
            - "8025:8025"
    
    app:
        build: app
        image: leopku/discourse:1.3.10-official
        env_file:
            - .env
        volumes: 
            - /etc/localtime:/etc/localtime:ro
            - ./volumes/discourse/public:/var/www/discourse/public
            - ./volumes/discourse/plugins:/var/www/discourse/plugins
            - ./volumes/nginx:/etc/nginx
        links:
            - redis
            - db
            - mail
